### ISSUE TITLE
MicroView demo does not compile on Arduino 1.6.3 IDE

### ISSUE THREAD

**Issue by vitormhenrique** [geekammo/MicroView-Arduino-Library#29]
Getting the following message when trying to compile the demo test on arduino 1.6.3

```
Arduino: 1.6.3 (Mac OS X), TD: 1.22, Board: "Arduino Uno"

Build options changed, rebuilding all
In file included from /Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:10:0:
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:18:18: error: variable 'monthStr1' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr1[] PROGMEM = "January";
                  ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:19:18: error: variable 'monthStr2' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr2[] PROGMEM = "February";
                  ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:20:18: error: variable 'monthStr3' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr3[] PROGMEM = "March";
                  ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:21:18: error: variable 'monthStr4' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr4[] PROGMEM = "April";
                  ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:22:18: error: variable 'monthStr5' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr5[] PROGMEM = "May";
                  ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:23:18: error: variable 'monthStr6' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr6[] PROGMEM = "June";
                  ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:24:18: error: variable 'monthStr7' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr7[] PROGMEM = "July";
                  ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:25:18: error: variable 'monthStr8' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr8[] PROGMEM = "August";
                  ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:26:18: error: variable 'monthStr9' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr9[] PROGMEM = "September";
                  ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:27:19: error: variable 'monthStr10' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr10[] PROGMEM = "October";
                   ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:28:19: error: variable 'monthStr11' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr11[] PROGMEM = "November";
                   ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:29:19: error: variable 'monthStr12' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthStr12[] PROGMEM = "December";
                   ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:31:22: error: variable 'monthNames_P' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 PGM_P monthNames_P[] PROGMEM = 
                      ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:37:26: error: variable 'monthShortNames_P' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char monthShortNames_P[] PROGMEM = "ErrJanFebMarAprMayJunJulAugSepOctNovDec";
                          ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:39:16: error: variable 'dayStr0' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char dayStr0[] PROGMEM = "Err";
                ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:40:16: error: variable 'dayStr1' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char dayStr1[] PROGMEM = "Sunday";
                ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:41:16: error: variable 'dayStr2' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char dayStr2[] PROGMEM = "Monday";
                ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:42:16: error: variable 'dayStr3' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char dayStr3[] PROGMEM = "Tuesday";
                ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:43:16: error: variable 'dayStr4' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char dayStr4[] PROGMEM = "Wednesday";
                ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:44:16: error: variable 'dayStr5' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char dayStr5[] PROGMEM = "Thursday";
                ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:45:16: error: variable 'dayStr6' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char dayStr6[] PROGMEM = "Friday";
                ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:46:16: error: variable 'dayStr7' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char dayStr7[] PROGMEM = "Saturday";
                ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:48:20: error: variable 'dayNames_P' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 PGM_P dayNames_P[] PROGMEM = { dayStr0,dayStr1,dayStr2,dayStr3,dayStr4,dayStr5,dayStr6,dayStr7};
                    ^
/Volumes/Macintosh HD/vitormhenrique/Documents/Arduino/libraries/Time/DateStrings.cpp:49:24: error: variable 'dayShortNames_P' must be const in order to be put into read-only section by means of '__attribute__((progmem))'
 char dayShortNames_P[] PROGMEM = "ErrSunMonTueWedThrFriSat";
                        ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.
```

**Comment by jpliew** [comment]
Hey mate,
This is a problem with the Time library. It was written by Paul here
https://github.com/PaulStoffregen/Time

You might want to try their latest code from github, if still not working file an issue in his github.

Hope this helps.

Cheers
JP

**Comment by MLXXXp** [comment]
I believe I had the same problem with the *Time* library. Here's the changes that I made:
```diff
--- DateStrings.cpp.org	2014-07-13 16:21:52.766245128 -0400
+++ DateStrings.cpp	2014-07-13 16:30:08.574254436 -0400
@@ -38,7 +38,7 @@
 const char monthStr11[] PROGMEM = "November";
 const char monthStr12[] PROGMEM = "December";
 
-PGM_P monthNames_P[] PROGMEM = 
+PGM_P const monthNames_P[] PROGMEM = 
 {
     "",monthStr1,monthStr2,monthStr3,monthStr4,monthStr5,monthStr6,
 	monthStr7,monthStr8,monthStr9,monthStr10,monthStr11,monthStr12
@@ -55,8 +55,8 @@
 const char dayStr6[] PROGMEM = "Friday";
 const char dayStr7[] PROGMEM = "Saturday";
 
-PGM_P dayNames_P[] PROGMEM = { dayStr0,dayStr1,dayStr2,dayStr3,dayStr4,dayStr5,dayStr6,dayStr7};
-char dayShortNames_P[] PROGMEM = "ErrSunMonTueWedThrFriSat";
+PGM_P const dayNames_P[] PROGMEM = { dayStr0,dayStr1,dayStr2,dayStr3,dayStr4,dayStr5,dayStr6,dayStr7};
+const char dayShortNames_P[] PROGMEM = "ErrSunMonTueWedThrFriSat";
 
 /* functions to return date strings */
 ```

**Comment by jpliew** [comment]
Hey @vitormhenrique ,

Scott replied to you via email, however for an unknown reason, his reply did not get in here. Please see his reply below:

---

I believe I had the same problem with the Time library. Here's the changes that I made:

--- DateStrings.cpp.org 2014-07-13 16:21:52.766245128 -0400
+++ DateStrings.cpp 2014-07-13 16:30:08.574254436 -0400
@@ -38,7 +38,7 @@
 const char monthStr11[] PROGMEM = "November";
 const char monthStr12[] PROGMEM = "December";

-PGM_P monthNames_P[] PROGMEM = 
+PGM_P const monthNames_P[] PROGMEM = 
 {
     "",monthStr1,monthStr2,monthStr3,monthStr4,monthStr5,monthStr6,
    monthStr7,monthStr8,monthStr9,monthStr10,monthStr11,monthStr12
@@ -55,8 +55,8 @@
 const char dayStr6[] PROGMEM = "Friday";
 const char dayStr7[] PROGMEM = "Saturday";

-PGM_P dayNames_P[] PROGMEM = { dayStr0,dayStr1,dayStr2,dayStr3,dayStr4,dayStr5,dayStr6,dayStr7};
-char dayShortNames_P[] PROGMEM = "ErrSunMonTueWedThrFriSat";
+PGM_P const dayNames_P[] PROGMEM = { dayStr0,dayStr1,dayStr2,dayStr3,dayStr4,dayStr5,dayStr6,dayStr7};
+const char dayShortNames_P[] PROGMEM = "ErrSunMonTueWedThrFriSat";

 /\* functions to return date strings */

**Comment by MLXXXp** [comment]
I deleted the reply because after I posted it, I found that all the necessary changes had been made to the latest version in the GitHub _Time_ repository that @jpliew referred to:
https://github.com/PaulStoffregen/Time

I tested this latest version in place of the older one I had modified on my system and it worked fine. So, I'd recommend just installing the latest _Time_ library.

**Comment by vitormhenrique** [comment]
Thanks guys!
